<a href="https://colab.research.google.com/github/arunyeldi/pytorch-deep-learning/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

In [6]:
import torch
import pandas as pd
import numpy as numpy
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


## Introduction to Tensors

## Creating Tensors

PyTorch tensors are created using torch.tensor()

In [7]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [8]:
scalar.ndim

0

In [9]:
# Ste tensor back as Python int
scalar.item()

7

In [10]:
# Vector
vector = torch.tensor([5, 5])
vector

tensor([5, 5])

In [11]:
vector.ndim

1

In [12]:
vector.shape

torch.Size([2])

In [13]:
# MATRIX
MATRIX = torch.tensor([[2, 5], [3, 4]])
MATRIX

tensor([[2, 5],
        [3, 4]])

In [14]:
MATRIX.ndim

2

In [15]:
MATRIX[1]

tensor([3, 4])

In [17]:
MATRIX.shape

torch.Size([2, 2])

In [29]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3, 4],
                        [4, 5, 6, 8],
                        [7, 8, 9, 0],
                        [10, 11, 12, 13]]])
TENSOR

tensor([[[ 1,  2,  3,  4],
         [ 4,  5,  6,  8],
         [ 7,  8,  9,  0],
         [10, 11, 12, 13]]])

In [30]:
TENSOR.ndim

3

In [31]:
TENSOR.shape

torch.Size([1, 4, 4])

In [36]:
TENSOR[0][2]

tensor([7, 8, 9, 0])

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers

In [44]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.9348, 0.0125, 0.8501, 0.4976],
        [0.3867, 0.6731, 0.5324, 0.3065],
        [0.8521, 0.9980, 0.3155, 0.4696]])

In [45]:
random_tensor.ndim

2

In [49]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (3, 224, 224)) # colour channels (R, G, B), height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

## Zeros and ones

In [51]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [54]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [55]:
ones.dtype

torch.float32

In [56]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [61]:
# Use torch.range()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

In [86]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None, # what datatype is the tensor (e.g. float32 or float16)
                               device = None, # what device is your tensor on
                               requires_grad = False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [87]:
float_32_tensor.dtype

torch.float32

In [88]:
float_16_tensor = float_32_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [90]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

In [94]:
int_32_tensor = torch.tensor([3, 6, 9], dtype = torch.long)
int_32_tensor

tensor([3, 6, 9])

In [95]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

### Getting information from tensors

1. Tensors not right datatype - to do get datatype from a tensor, can use tensor.datatype
2. Tensors not right shape - to get shape from a tensor, can use tensor.shape
3. Tensors not on the right device - to get device from a tensor, can use tensor.device

In [99]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.0847, 0.0794, 0.8550, 0.3754],
        [0.3403, 0.3035, 0.4400, 0.2014],
        [0.0204, 0.8118, 0.8351, 0.1080]])

In [100]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.0847, 0.0794, 0.8550, 0.3754],
        [0.3403, 0.3035, 0.4400, 0.2014],
        [0.0204, 0.8118, 0.8351, 0.1080]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operation includes:
* Addition
* Subtraction
* Multiplication(element-wise)
* Division
* Matrix multiplication

In [111]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [112]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [113]:
tensor

tensor([1, 2, 3])

In [114]:
# subtract 10
tensor - 10

tensor([-9, -8, -7])

In [115]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [116]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [117]:
torch.sub(tensor, 10)

tensor([-9, -8, -7])

In [118]:
torch.div(tensor, 10)

tensor([0.1000, 0.2000, 0.3000])

###Matrix multiplication

Two main ways of performing multiplication in nural networks and deep learning:

1. Element-wise Multiplication
2. Matrix Multiplication (dot product)


In [119]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [120]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [133]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.69 ms, sys: 0 ns, total: 1.69 ms
Wall time: 1.71 ms


In [134]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 85 µs, sys: 970 µs, total: 1.05 ms
Wall time: 914 µs


tensor(14)